spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb
    username: task
    password: p@ssw0rd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  email:
    to: recipient@example.com

server:
  error:
    include-message: always
